-- Ayah Quest — Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.users (
  telegram_id text primary key,
  username text,
  first_name text not null default '',
  last_name text not null default '',
  display_name text,
  is_pro boolean not null default false,
  xp integer not null default 0,
  streak integer not null default 0,
  total_answered integer not null default 0,
  total_correct integer not null default 0,
  last_active_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telebirr_requests (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.users(telegram_id) on delete cascade,
  reference text not null,
  amount numeric(12,2) not null default 25,
  phone text,
  recipient_name text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  receipt_received boolean not null default false,
  receipt_file_id text,
  submitted_at timestamptz not null default now(),
  receipt_received_at timestamptz,
  approved_at timestamptz,
  rejected_at timestamptz
);

create unique index if not exists telebirr_one_pending_per_user
on public.telebirr_requests(telegram_id)
where status = 'pending';

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.users(telegram_id) on delete cascade,
  provider text not null check (provider in ('telegram_stars','telebirr')),
  amount numeric(12,2) not null,
  currency text not null,
  charge_id text,
  payload text,
  reference text,
  created_at timestamptz not null default now()
);

create unique index if not exists payments_unique_stars_charge
on public.payments(charge_id)
where charge_id is not null;

create table if not exists public.quiz_history (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.users(telegram_id) on delete cascade,
  score integer not null default 0,
  total integer not null default 10,
  correct integer not null default 0,
  xp integer not null default 0,
  mode text not null default 'core',
  created_at timestamptz not null default now()
);

create index if not exists quiz_history_user_created_idx
on public.quiz_history(telegram_id, created_at desc);

-- Security: the backend uses the Supabase secret/service-role key.
-- Do NOT put that key in index.html, Vercel frontend code, or Telegram Mini App JS.
-- These tables are intentionally not exposed to the browser directly.
alter table public.users enable row level security;
alter table public.telebirr_requests enable row level security;
alter table public.payments enable row level security;
alter table public.quiz_history enable row level security;
